source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'FMLayouts'

platform :ios, '7.0'

pod 'FMLayouts', :path=>'../../'

target 'FMLayouts' do
end

target 'FMLayoutsTests' do
end

